baseurl = "https://ludobaka.github.io/"
theme = "hugo-geo"
languageCode = "en-us"
title = "Ludovic Bailly Personal Website"
disqusShortname = "ludobaka-github-io"
relativeURLs = false
enableRobotsTXT = true
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"

	analytics = "UA-98630525-1"

	email = "ludo.bailly@gmail.com"

	profilepic = "img/profile.png"

	title = "Ludovic Bailly"
	subtitle = "Data Processing & 3D Modeling Engineer"
	description = "I'm Ludovic Bailly, a Software Engineer specialized in 3D Data Visualization. I aim to participate in building the tools of the future with a strong interest in VR and AR."

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://www.linkedin.com/in/lbailly/"
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/ludobaka"
	[[params.socialbuttons]]
	faicon = "stack-overflow"
	url = "https://stackoverflow.com/u/5398225/"
	[[params.socialbuttons]]
	faicon = "soundcloud"
	url = "https://soundcloud.com/ludobailly"

	[[params.navlinks]]
	name = "Blog"
	url = "post/"

	# [[params.navlinks]]
	# name = "Tutorials"
	# url = "tutorial/"

    [[params.navlinks]]
    name = "Resume"
    url = "resume/"

    [[params.navlinks]]
    name = "About"
    url = "about"
